learning_log/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('learning_logs.urls',namespace='learning_logs')),
]

learning_logs/urls.py
'''Define URL patterns for learning logs'''

from django.conf.urls import url
from . import views

''' A list of avialable page that can be requested from learning_logs app'''
urlpatterns = [
	# Home Page
	url(r'^$', views.index,name='index'),
	url(r'^topics/$', views.topics,name='topics'),
	
	#The r tells Python to interpret the following string as a raw string, 
	#and the quotes tell Python where the regular expression begins and ends. 
	#The caret (^) tells Python to find the beginning of the string, 
	#and the dollar sign tells Python to look for the end of the string. 
	
	#In its entirety, this expression tells Python to look for a URL with nothing between the beginning and end of the URL.
	#Python ignores the base URL for the project (http://localhost:8000/), 
	#so an empty regular expression matches the base URL. 
	#Any other URL will not match this expression, 
	#and Django will return an error page if the URL requested doesn’t match any existing URL patterns.
]

learning_logs/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
	"""A Topic the user is learning about"""
	text=models.CharField(max_length=200)
	date_added=models.DateTimeField(auto_now_add=True)
	
	def __str__(self):
		"""return a string representation of the model."""
		return self.text
		
		
class Entry(models.Model):
	'''Sometihing specific learned about a topic'''
	topic=models.ForeignKey(Topic)
	text=models.TextField()
	date_added=models.DateTimeField(auto_now_add=True)
	
	class Meta:
		verbose_name_plural='entries'
		
	def __str__(self):
		"""return a string representation"""
		return self.text[:50]+"..."
		
	

learning_logs/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
	'''The home page for Learning Log'''
	return render(request, 'learning_logs/index.html')

def topics(request):
	'''show all topics.'''
	topics=Topic.objects.order_by('date_added')
	context={'topics':topics}
	return render(request,'learning_logs/topics.html',context)

learning_logs/templates/learning_logs/base.html
<p>
	<a herf="{% url 'learning_logs:index' %}">Learning Log</a> - <!--Dash!!!!-->
	<!-- matching the url pattern defined in learning_logs/urls.py with name 'index'-->
	<a herf="{% url 'learning_logs:topics' %}">Topics:</a>
</p>

{% block content %}{% endblock content %}
<!--this block named content, children template will define what kind of information that goes into the block-->

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block content %}
	<p>Learning Log helps you keep track of your learningm for any topic you're learning about.</p>
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block content %}
	<p>Topics</p>
	<ul> <!--unordered list-->
		{% for topic in topics %}
			<li>{{ topic }}</li> <!--<li> list-->
			<!--Braces just indicate to Django that we’re using a template variable.-->
		{% empty %}
			<li>No topics have been added yet.</li>
		{% endfor %}
	</ul>
{% endblock content %}